version: 0.2

env:
  parameter-store:
    CODECOV_TOKEN: "daswag-cli-codecov-token"
    SONAR_TOKEN: "daswag-cli-sonar-token"

phases:
  install:
    runtime-versions:
      nodejs: 12
  pre_build:
    commands:
      - make install
      - make install-sonar
  build:
    commands:
      - make test
      - make codecov
cache:
  paths:
    - 'node_modules/**/*'
